### ISSUE TITLE
Error while downloading an image - No such file or directory /tmp/deemix-imgs

### ISSUE THREAD

**Issue by racedale** [RandomNinjaAtk/docker-lidarr-extended#171]
Some errors with downloading that seem to end up marking the album as not found.
Running via docker-compose, on Synology. 

```
Error while downloading an image, you should report this to the developers: [Errno 2] No such file or directory: '/tmp/deemix-imgs/alb782032_1400.jpg'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/deemix/downloader.py", line 67, in downloadImage
    with open(path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/deemix-imgs/alb782032_1400.jpg'
```
```
Suburban Legends - Natasha [Errno 2] No such file or directory: '/downloads-lidarr-extended/incomplete/113 - Natasha.mp3'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mutagen/_util.py", line 250, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/downloads-lidarr-extended/incomplete/113 - Natasha.mp3'
```
``` 
[album_782032_9] Suburban Legends - Natasha :: [Errno 2] No such file or directory: '/downloads-lidarr-extended/incomplete/113 - Natasha.mp3'
```

**Comment by RandomNinjaAtk** [comment]
Seems like a deemix issue, you should report it in those support channels.
