### ISSUE TITLE
ModuleNotFoundError: No module named 'jellyfish._rustyfish'

### ISSUE THREAD

**Issue by wieluk** [RandomNinjaAtk/docker-lidarr-extended#256]
When files are being processed with beets I am getting this error:

```
2023-06-15 12:59:47 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: Success

2023-06-15 12:59:47 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: Skipping download quality check... (enable by setting: requireQuality=true)

2023-06-15 12:59:47 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: Logging 352625757 as successfully downloaded...

2023-06-15 12:59:47 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: Processing files with beets...

Traceback (most recent call last):

  File "/usr/bin/beet", line 5, in <module>

    from beets.ui import main

  File "/usr/lib/python3.11/site-packages/beets/ui/__init__.py", line 39, in <module>

    from beets.autotag import mb

  File "/usr/lib/python3.11/site-packages/beets/autotag/__init__.py", line 23, in <module>

    from .hooks import (  # noqa

  File "/usr/lib/python3.11/site-packages/beets/autotag/hooks.py", line 26, in <module>

    from jellyfish import levenshtein_distance

  File "/usr/lib/python3.11/site-packages/jellyfish/__init__.py", line 3, in <module>

    from ._rustyfish import *

ModuleNotFoundError: No module named 'jellyfish._rustyfish'

2023-06-15 12:59:48 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: ERROR :: Unable to match using beets to a musicbrainz release...

2023-06-15 12:59:48 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: Converting Flac Audio to MP3 (128k)

2023-06-15 12:59:48 :: Audio :: 1.0.9 :: 1 :: missing :: 63 of 399 :: Bonez MC :: Palmen aus Plastik :: Album :: Adding Replaygain Tags using r128gain
```

do you know what the problem is?

My version is: 
```
Presents: lidarr-extended (1.0.9)
Docker Version: amd64-1.0.34
```

**Comment by wieluk** [comment]
No I did not change anything with beets. In my yaml the beets settings are default
```
      - enableBeetsTagging=true
      - beetsMatchPercentage=90
```

**Comment by RandomNinjaAtk** [comment]
Try the latest update.

**Comment by wieluk** [comment]
No, I am still getting the same error

**Comment by RandomNinjaAtk** [comment]
I'll look at it further when I have some free cycles...

**Comment by RandomNinjaAtk** [comment]
Try the latest update, not sure if it will resolve it, but it might...

**Comment by RandomNinjaAtk** [comment]
I think this might now be fully squashed, please update to latest and give it another go...

**Comment by jackmaninov** [comment]
Seems to be working for me
